# Generated by Django 4.2.3 on 2023-07-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_item_cart_item_category_item_name_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
    ]
