# Generated by Django 4.2.3 on 2023-07-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item_app', '0003_remove_item_cart'),
        ('cart_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='cart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cart_app.cart'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='item',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='item_app.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
